### ISSUE TITLE
Is it possible to use non square images ?

### ISSUE THREAD

**Issue by bruno-31** [eboigne/PyTV#1]
Hi, thank you so much for the nice work!
It seems that it is only possible to use square images in your code, why?

**Comment by eboigne** [comment]
Hi, yes that's true, that's how it is implemented for now. That's because I mostly used TV for CT reconstruction for which images are typically square, see [https://github.com/eboigne/PyRAMID-CT](https://github.com/eboigne/PyRAMID-CT).

I don't really plan to update the code for non-square images right now. But, as a quick work-around, I'd recommend filling in your images with zeros into square images. You'll loose some performance, but that should be reasonable if your images are close to square.

**Comment by bruno-31** [comment]
Thank you !
